# Generated by Django 5.0.3 on 2024-03-07 14:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pressure_Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='default', max_length=200)),
                ('installation_date', models.DateTimeField(default=datetime.datetime(2024, 3, 7, 17, 53, 4, 441754), verbose_name='installation date')),
                ('latitude', models.IntegerField(default=0)),
                ('longitude', models.IntegerField(default=0)),
                ('serial_number', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pressure_Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='default', max_length=200)),
                ('date_time', models.DateTimeField(default=datetime.datetime(2024, 3, 7, 17, 53, 4, 441754), verbose_name='installation date')),
                ('value', models.FloatField(default=0.0)),
                ('sensor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pressure_sensor.pressure_sensor', verbose_name='Sensor ID')),
            ],
        ),
    ]
