# Generated by Django 5.0.3 on 2024-03-07 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pressure_sensor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressure_reading',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 7, 18, 19, 38, 24452), verbose_name='installation date'),
        ),
        migrations.AlterField(
            model_name='pressure_sensor',
            name='installation_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 7, 18, 19, 38, 24452), verbose_name='installation date'),
        ),
    ]
