# Generated by Django 5.0.3 on 2024-05-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pressure_sensor", "0007_alter_pressure_reading_date_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pressure_reading",
            name="row_value",
            field=models.FloatField(default=0.0),
        ),
    ]
