# Generated by Django 5.0.3 on 2024-05-09 11:16

from django.db import migrations, models


def add_row_value(apps, schema_editor):
    Pressure_Reading = apps.get_model("pressure_sensor", "Pressure_Reading")

    for obj in Pressure_Reading.objects.all():

        obj.row_value = obj.value
        obj.save()


# def remove_row_value(apps, schema_editor):
#     Pressure_Reading = apps.get_model("Pressure_Sensor", "Pressure_Reading")
#
#     Pressure_Reading.objects.update(row_value=None)


class Migration(migrations.Migration):

    dependencies = [
        ("pressure_sensor", "0008_pressure_reading_row_value"),
    ]

    operations = [
        migrations.RunPython(add_row_value),
    ]
