# Generated by Django 5.0.3 on 2024-03-20 00:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionText', models.CharField(default='Question', max_length=200)),
                ('datePublished', models.DateTimeField(default=datetime.datetime(2024, 3, 20, 3, 28, 32, 331768), verbose_name='Date Published')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstChoice', models.CharField(default='First', max_length=200)),
                ('SecChoice', models.CharField(default='Sec', max_length=200)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='polls.question')),
            ],
        ),
    ]
