# Generated by Django 5.0.3 on 2024-04-06 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_question_datepublished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='datePublished',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 6, 22, 48, 8, 51012), verbose_name='Date Published'),
        ),
    ]
