# Generated by Django 5.0.3 on 2024-04-06 20:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0004_alter_question_datepublished"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="choice",
            name="question",
        ),
        migrations.AlterField(
            model_name="question",
            name="datePublished",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 6, 23, 40, 47, 867684),
                verbose_name="Date Published",
            ),
        ),
        migrations.CreateModel(
            name="QuestionChoices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="polls.choice"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="polls.question"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="choice",
            name="question",
            field=models.ManyToManyField(
                through="polls.QuestionChoices", to="polls.question"
            ),
        ),
    ]
