# Generated by Django 5.0.3 on 2024-05-09 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0005_remove_choice_question_alter_question_datepublished_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="datePublished",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 9, 14, 13, 28, 973449),
                verbose_name="Date Published",
            ),
        ),
    ]
